package view.lectures;

import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionListener;

import university.LectureComment;
import view.View;


public class CommentView implements View {

    private JPanel mainPane;
    private JPanel createPane;
    private JPanel listPane;
    private JPanel actionPane;
    private JList dataList;
    private JTextField inputField;
    private JButton addButton;
    private JButton deleteButton;

    public CommentView() {
        DefaultListModel listModel = new DefaultListModel();
        dataList.setCellRenderer(new CommentCellRenderer(300));
    }

    //<editor-fold desc="Actions">
    public void showOptions() {
        deleteButton.setVisible(true);
    }

    public void hideOptions() {
        deleteButton.setVisible(false);
    }
    //</editor-fold>

    //<editor-fold desc="Get/Set Section">
    @Override
    public JPanel getMainPane() {
        return mainPane;
    }

    public Object getObject(int index) {
        return dataList.getModel().getElementAt(index);
    }

    public String getInputText() {
        return inputField.getText();
    }

    public void clearInputField() {
        inputField.setText("");
    }

    public void setList(LectureComment[] commentTable) {
        CommentListModel listModel = new CommentListModel();
        for (LectureComment comment : commentTable) {
            listModel.addElement(comment);
        }
        //dataList.setListData(commentTable);
        //dataList.removeAll();
        dataList.setModel(listModel);
    }
    //</editor-fold>

    //<editor-fold desc="Listener Section">
    public void setDeletionListener(ActionListener l) {
        this.deleteButton.addActionListener(l);
    }

    public void setCreationListener(ActionListener l) {
        this.addButton.addActionListener(l);
    }

    public void setSelectionListener(ListSelectionListener l) {
        this.dataList.getSelectionModel().addListSelectionListener(l);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setPreferredSize(new Dimension(500, 300));
        mainPane.setVerifyInputWhenFocusTarget(false);
        createPane = new JPanel();
        createPane.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        createPane.setPreferredSize(new Dimension(500, 50));
        mainPane.add(createPane, BorderLayout.NORTH);
        inputField = new JTextField();
        inputField.setPreferredSize(new Dimension(350, 40));
        createPane.add(inputField);
        addButton = new JButton();
        addButton.setText("Comment");
        createPane.add(addButton);
        actionPane = new JPanel();
        actionPane.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        actionPane.setPreferredSize(new Dimension(500, 50));
        mainPane.add(actionPane, BorderLayout.SOUTH);
        deleteButton = new JButton();
        deleteButton.setText("Remove");
        actionPane.add(deleteButton);
        listPane = new JPanel();
        listPane.setLayout(new BorderLayout(0, 0));
        mainPane.add(listPane, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(500, 200));
        listPane.add(scrollPane1, BorderLayout.CENTER);
        dataList = new JList();
        scrollPane1.setViewportView(dataList);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

    //</editor-fold>

    //<editor-fold desc="Other Class Section">
    class CommentListModel extends DefaultListModel {

    }

    class CommentCellRenderer extends DefaultListCellRenderer {

        public static final String HTML_REG = "<html>\n" +
                "<body style='width: %dpx'>\n" +
                "<p><strong>%s</strong> - %s</p>\n" +
                "<p style=\"text-align: right;\"><span style=\"color: #999999;\"><em>%s</em></span></p>\n" +
                "</html>";

        public static final String HTML_ANSWER = "<html>\n" +
                "<body style='width: %dpx'>\n" +
                "<p style=\"padding-left: 30px;\"><strong>%s</strong> - %s</p>\n" +
                "<p style=\"text-align: right;\"><span style=\"color: #999999;\"><em>%s</em></span></p>\n" +
                "</html>";

        private int width;

        public CommentCellRenderer(int width) {
            this.width = width;
        }

        @Override
        public Component getListCellRendererComponent(JList list, Object value,
                                                      int index, boolean isSelected, boolean cellHasFocus) {
            LectureComment comment = (LectureComment) value;

            this.setToolTipText("" + comment.getId());
            String template = comment.getAnswer() ? HTML_ANSWER : HTML_REG;
            String text = String.format(template, width, comment.getAuthor().getName(), comment.getText(),
                    comment.getDate() + " - " + comment.getTime());
            return super.getListCellRendererComponent(list, text, index, isSelected,
                    cellHasFocus);
        }

    }
    //</editor-fold>

}
