package view.lectures;

import view.View;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class DetailsView implements View {

    private JPanel mainPane;
    private JButton joinDropLectureButton;
    private JPanel buttonPane;
    private JPanel rightPane;
    private JPanel detailsPane;
    private JButton mapLocationButton;
    private JButton participantsButton;
    private JTextPane textPane;
    private JPanel leftPane;

    //<editor-fold desc="Getters & Setters">
    private void setPane(JPanel pane, JPanel paneContent) {
        pane.removeAll();
        pane.add(paneContent, BorderLayout.CENTER);
        pane.setPreferredSize(paneContent.getPreferredSize());
    }

    @Override
    public JPanel getMainPane() {
        return mainPane;
    }

    public JButton getJoinDropLectureButton() {
        return joinDropLectureButton;
    }

    public JButton getMapLocationButton() {
        return mapLocationButton;
    }

    public JButton getParticipantsButton() {
        return participantsButton;
    }

    public JPanel getRightPane() {
        return rightPane;
    }

    public void setRightPane(JPanel rightPane) {
        setPane(this.rightPane, rightPane);
    }

    public JPanel getDetailsPane() {
        return detailsPane;
    }
    //</editor-fold>

    //<editor-fold desc="Listener Section">
    public void setRowListener(ActionListener l) {
        joinDropLectureButton.addActionListener(l);
    }

    public void setMapListener(ActionListener l) {
        mapLocationButton.addActionListener(l);
    }

    public void setParticipantsButton(ActionListener l) {
        participantsButton.addActionListener(l);
    }

    public void setTextPane(String text) {
        textPane.setText(text);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setPreferredSize(new Dimension(1000, 300));
        rightPane = new JPanel();
        rightPane.setLayout(new BorderLayout(0, 0));
        rightPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(rightPane, BorderLayout.EAST);
        rightPane.setBorder(BorderFactory.createTitledBorder("Comments"));
        leftPane = new JPanel();
        leftPane.setLayout(new BorderLayout(0, 0));
        leftPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(leftPane, BorderLayout.WEST);
        leftPane.setBorder(BorderFactory.createTitledBorder("Details & Actions"));
        detailsPane = new JPanel();
        detailsPane.setLayout(new BorderLayout(0, 0));
        detailsPane.setMaximumSize(new Dimension(350, 300));
        leftPane.add(detailsPane, BorderLayout.EAST);
        textPane = new JTextPane();
        textPane.setPreferredSize(new Dimension(350, 300));
        detailsPane.add(textPane, BorderLayout.CENTER);
        buttonPane = new JPanel();
        buttonPane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        buttonPane.setPreferredSize(new Dimension(150, 10));
        buttonPane.setVerifyInputWhenFocusTarget(true);
        leftPane.add(buttonPane, BorderLayout.WEST);
        joinDropLectureButton = new JButton();
        joinDropLectureButton.setText("Join Lecture");
        joinDropLectureButton.setToolTipText("Click here to join the selected lecture");
        buttonPane.add(joinDropLectureButton);
        mapLocationButton = new JButton();
        mapLocationButton.setText("Map");
        buttonPane.add(mapLocationButton);
        participantsButton = new JButton();
        participantsButton.setText("Participants");
        buttonPane.add(participantsButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

    //</editor-fold>

}
