package view.lectures;

import view.Section;
import view.View;

import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.MouseListener;

public class TableView implements View {

    private JPanel mainPane;
    private JScrollPane leftPane;
    private JScrollPane rightPane;
    private JTable leftTable;
    private JTable rightTable;

    public TableView() {
        leftTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        rightTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    //<editor-fold desc="Getters">
    public JPanel getMainPane() {
        return mainPane;
    }

    public JTable getLeftTable() {
        return leftTable;
    }

    public JTable getRightTable() {
        return rightTable;
    }
    //</editor-fold>

    //<editor-fold desc="Listener Section">
    public void setRowListener(ListSelectionListener l) {
        leftTable.getSelectionModel().addListSelectionListener(l);
        rightTable.getSelectionModel().addListSelectionListener(l);
    }

    public void setHeaderListener(MouseListener l) {
        leftTable.getTableHeader().addMouseListener(l);
        rightTable.getTableHeader().addMouseListener(l);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setPreferredSize(new Dimension(1000, 300));
        leftPane = new JScrollPane();
        leftPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(leftPane, BorderLayout.WEST);
        leftPane.setBorder(BorderFactory.createTitledBorder("Joinable Lectures"));
        leftTable = new JTable();
        leftPane.setViewportView(leftTable);
        rightPane = new JScrollPane();
        rightPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(rightPane, BorderLayout.EAST);
        rightPane.setBorder(BorderFactory.createTitledBorder("Joined Lectures"));
        rightTable = new JTable();
        rightTable.setPreferredSize(new Dimension(500, 300));
        rightPane.setViewportView(rightTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

    //</editor-fold>

    //<editor-fold desc="---">
    //
    //</editor-fold>

}
