package view;

import javax.swing.*;
import java.awt.*;

public class AppFrame extends JFrame implements View {

    private JPanel mainPane;
    private JPanel menuPane;
    private JTabbedPane tabPane;
    private JPanel loginPane;
    private JPanel lecturesPane;
    private JPanel studentsPane;

    public AppFrame() {
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setTitle("University App feat. Team 13");
        this.add(mainPane);
    }

    //<editor-fold desc="Open / Close Window">
    public void open() {
        this.pack();
        this.setVisible(true);
    }

    public void close() {
        this.setVisible(false);
        this.dispose();
    }
    //</editor-fold>

    //<editor-fold desc="Getters & Setters">
    private void setPane(JPanel pane, JPanel paneContent) {
        pane.removeAll();
        pane.add(paneContent, BorderLayout.CENTER);
        pane.setPreferredSize(paneContent.getPreferredSize());
        this.pack();
    }

    public JPanel getMenuPane() {
        return menuPane;
    }

    public void setMenuPane(View menuView) {
        setPane(this.menuPane, menuView.getMainPane());
    }

    public JPanel getLogInPane() {
        return loginPane;
    }

    public void setLogInPane(View logInView) {
        setPane(this.loginPane, logInView.getMainPane());
    }

    public JPanel getLecturesPane() {
        return lecturesPane;
    }

    public void setLecturesPane(View lecturesView) {
        setPane(this.lecturesPane, lecturesView.getMainPane());
    }

    public JPanel getStudentsPane() {
        return studentsPane;
    }

    public void setStudentsPane(View peopleView) {
        setPane(this.studentsPane, peopleView.getMainPane());
    }

    public JPanel getMainPane() {
        return mainPane;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-13602637)), null));
        menuPane = new JPanel();
        menuPane.setLayout(new BorderLayout(0, 0));
        menuPane.setPreferredSize(new Dimension(0, 30));
        mainPane.add(menuPane, BorderLayout.NORTH);
        tabPane = new JTabbedPane();
        mainPane.add(tabPane, BorderLayout.CENTER);
        loginPane = new JPanel();
        loginPane.setLayout(new BorderLayout(0, 0));
        tabPane.addTab("Login", loginPane);
        lecturesPane = new JPanel();
        lecturesPane.setLayout(new BorderLayout(0, 0));
        lecturesPane.setEnabled(true);
        tabPane.addTab("Lectures", lecturesPane);
        studentsPane = new JPanel();
        studentsPane.setLayout(new BorderLayout(0, 0));
        studentsPane.setEnabled(true);
        tabPane.addTab("Students", studentsPane);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

    //<editor-fold desc="---">
    //
    //</editor-fold>


}
