package view;

import controller.ButtonListener;

import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import java.awt.*;

public class LecturesDetailsView implements View {

    private JPanel mainPane;
    private JButton joinLectureButton;
    private JButton dropLectureButton;

    //<editor-fold desc="Get Section">
    @Override
    public JPanel getMainPane() {
        return mainPane;
    }

    public JButton getJoinLectureButton() {
        return joinLectureButton;
    }

    public JButton getDropLectureButton() {
        return dropLectureButton;
    }
    //</editor-fold>

    //<editor-fold desc="Listener Section">
    public void setRowListener(ButtonListener l) {
        joinLectureButton.addActionListener(l);
        dropLectureButton.addActionListener(l);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setPreferredSize(new Dimension(0, 100));
        joinLectureButton = new JButton();
        joinLectureButton.setText("Join Lecture");
        joinLectureButton.setToolTipText("Click here to join the selected lecture");
        mainPane.add(joinLectureButton, BorderLayout.WEST);
        dropLectureButton = new JButton();
        dropLectureButton.setText("Drop Lecture");
        dropLectureButton.setToolTipText("Click here to drop the selected lecture");
        mainPane.add(dropLectureButton, BorderLayout.EAST);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
    //</editor-fold>


}
