package view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import controller.ButtonListener;

import javax.swing.*;
import java.awt.*;

public class LecturesDetailsView implements View {

    private JPanel mainPane;
    private JButton joinDropLectureButton;
    private JPanel buttonPane;
    private JPanel commentPane;
    private JPanel detailsPane;

    //<editor-fold desc="Get Section">
    @Override
    public JPanel getMainPane() {
        return mainPane;
    }

    public JButton getJoinDropLectureButton() {
        return joinDropLectureButton;
    }

    public JPanel getCommentPane() {
        return commentPane;
    }

    public JPanel getDetailsPane() {
        return detailsPane;
    }
    //</editor-fold>

    //<editor-fold desc="Listener Section">
    public void setRowListener(ButtonListener l) {
        joinDropLectureButton.addActionListener(l);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setPreferredSize(new Dimension(0, 100));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPane.add(panel1, BorderLayout.WEST);
        joinDropLectureButton = new JButton();
        joinDropLectureButton.setText("Join Lecture");
        joinDropLectureButton.setToolTipText("Click here to join the selected lecture");
        panel1.add(joinDropLectureButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainPane.add(scrollPane1, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

    //</editor-fold>


}
