package view.students;

import view.View;

import javax.swing.*;
import java.awt.*;

public class DetailsStudents implements View {
    private JPanel mainPane;
    private JPanel leftPane;
    private JPanel rightPane;
    private JPanel detailsPane;
    private JTextPane textPane;
    private JPanel buttonPane;
    private JButton addRemoveFriendButton;
    private JButton detailsButton;

    @Override
    public JPanel getMainPane() {
        return mainPane;
    }

    public JPanel getLeftPane() {
        return leftPane;
    }

    public JPanel getRightPane() {
        return rightPane;
    }

    public JPanel getDetailsPane() {
        return detailsPane;
    }

    public JTextPane getTextPane() {
        return textPane;
    }

    public JPanel getButtonPane() {
        return buttonPane;
    }

    public JButton getAddRemoveFriendButton() {
        return addRemoveFriendButton;
    }

    public JButton getDetailsButton() {
        return detailsButton;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setPreferredSize(new Dimension(1000, 300));
        mainPane.setBorder(BorderFactory.createTitledBorder(""));
        rightPane = new JPanel();
        rightPane.setLayout(new BorderLayout(0, 0));
        rightPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(rightPane, BorderLayout.EAST);
        rightPane.setBorder(BorderFactory.createTitledBorder("Additional"));
        leftPane = new JPanel();
        leftPane.setLayout(new BorderLayout(0, 0));
        leftPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(leftPane, BorderLayout.WEST);
        leftPane.setBorder(BorderFactory.createTitledBorder("Details & Actions"));
        detailsPane = new JPanel();
        detailsPane.setLayout(new BorderLayout(0, 0));
        detailsPane.setMaximumSize(new Dimension(350, 300));
        detailsPane.setPreferredSize(new Dimension(350, 300));
        leftPane.add(detailsPane, BorderLayout.EAST);
        textPane = new JTextPane();
        detailsPane.add(textPane, BorderLayout.CENTER);
        buttonPane = new JPanel();
        buttonPane.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        buttonPane.setOpaque(false);
        buttonPane.setPreferredSize(new Dimension(150, 10));
        leftPane.add(buttonPane, BorderLayout.WEST);
        addRemoveFriendButton = new JButton();
        addRemoveFriendButton.setText("Add");
        buttonPane.add(addRemoveFriendButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}
