package view.students;

import com.intellij.uiDesigner.core.GridLayoutManager;
import view.Section;
import view.View;

import javax.swing.*;
import java.awt.*;

public class StudentsView implements View {

    private JPanel mainPane;
    private JPanel upperPane;
    private JPanel lowerPane;
    private JSeparator centerSep;

    //<editor-fold desc="Getters & Setters">
    @Override
    public JPanel getMainPane() {
        return mainPane;
    }

    public void setView(View view, Section section) {
        JPanel pane;
        switch (section) {
            case Upper:
                pane = upperPane;
                break;
            case Lower:
                pane = lowerPane;
                break;
            default:
                throw new RuntimeException("Invalid section given: " + section.toString());
        }
        pane.removeAll();
        pane.add(view.getMainPane());
        pane.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        upperPane = new JPanel();
        upperPane.setLayout(new BorderLayout(0, 0));
        mainPane.add(upperPane, BorderLayout.NORTH);
        upperPane.setBorder(BorderFactory.createTitledBorder(""));
        lowerPane = new JPanel();
        lowerPane.setLayout(new BorderLayout(0, 0));
        mainPane.add(lowerPane, BorderLayout.SOUTH);
        centerSep = new JSeparator();
        mainPane.add(centerSep, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }

    //</editor-fold>
}
