package view.students;

import view.View;

import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.MouseListener;

public class TableViewStudents implements View {

    private JPanel mainPane;
    private JScrollPane leftPane;
    private JScrollPane rightPane;
    private JTable leftTable;
    private JTable rightTable;

    public TableViewStudents() {
        rightTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        leftTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public JPanel getMainPane() {
        return mainPane;
    }

    public JTable getRightTable() {
        return rightTable;
    }

    public JTable getLeftTable() {
        return leftTable;
    }

    public void setRowListener(ListSelectionListener l) {
        rightTable.getSelectionModel().addListSelectionListener(l);
        leftTable.getSelectionModel().addListSelectionListener(l);
    }

    public void setHeaderListener(MouseListener l) {
        rightTable.getTableHeader().addMouseListener(l);
        leftTable.getTableHeader().addMouseListener(l);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPane = new JPanel();
        mainPane.setLayout(new BorderLayout(0, 0));
        mainPane.setEnabled(true);
        mainPane.setPreferredSize(new Dimension(1000, 300));
        mainPane.setToolTipText("");
        leftPane = new JScrollPane();
        leftPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(leftPane, BorderLayout.WEST);
        leftPane.setBorder(BorderFactory.createTitledBorder("Not Friends"));
        leftTable = new JTable();
        leftPane.setViewportView(leftTable);
        rightPane = new JScrollPane();
        rightPane.setPreferredSize(new Dimension(500, 300));
        mainPane.add(rightPane, BorderLayout.EAST);
        rightPane.setBorder(BorderFactory.createTitledBorder("Friends"));
        rightTable = new JTable();
        rightPane.setViewportView(rightTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPane;
    }
}
