package view.students;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import view.View;

import javax.swing.*;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.MouseListener;

public class TableViewStudents implements View {

    private JPanel mainStudentsPane;
    private JScrollPane leftStudentsPane;
    private JScrollPane rightStudentsPane;
    private JTable rightStudentsTable;
    private JTable leftStudentsTable;

    public TableViewStudents() {
        leftStudentsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        rightStudentsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    @Override
    public JPanel getMainPane() {
        return mainStudentsPane;
    }

    public JTable getLeftStudentsTable() {
        return leftStudentsTable;
    }

    public JTable getRightStudentsTable() {
        return rightStudentsTable;
    }

    public void setRowListener(ListSelectionListener l) {
        leftStudentsTable.getSelectionModel().addListSelectionListener(l);
        rightStudentsTable.getSelectionModel().addListSelectionListener(l);
    }

    public void setHeaderListener(MouseListener l) {
        leftStudentsTable.getTableHeader().addMouseListener(l);
        rightStudentsTable.getTableHeader().addMouseListener(l);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainStudentsPane = new JPanel();
        mainStudentsPane.setLayout(new BorderLayout(0, 0));
        mainStudentsPane.setPreferredSize(new Dimension(1000, 300));
        mainStudentsPane.setToolTipText("");
        leftStudentsPane = new JScrollPane();
        leftStudentsPane.setPreferredSize(new Dimension(500, 300));
        mainStudentsPane.add(leftStudentsPane, BorderLayout.WEST);
        rightStudentsTable = new JTable();
        leftStudentsPane.setViewportView(rightStudentsTable);
        rightStudentsPane = new JScrollPane();
        rightStudentsPane.setPreferredSize(new Dimension(500, 300));
        mainStudentsPane.add(rightStudentsPane, BorderLayout.EAST);
        leftStudentsTable = new JTable();
        rightStudentsPane.setViewportView(leftStudentsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainStudentsPane;
    }
}
